### ISSUE TITLE
Antenna coordinates are invalid

### ISSUE THREAD

**Issue by bennahugo** [tart-telescope/tart2ms#12]
This is what the array looks like...
![image](https://user-images.githubusercontent.com/7934586/196473680-bbcbe205-5a82-4074-8d59-baf7ac0f6ba1.png)

**Comment by bennahugo** [comment]
This explains it though - these coordinates are supposed to be ITRF
coordinates. I'm guessing things fall apart when they are converted to WGS84

**Comment by tmolteno** [comment]
Will use astropy conversions to do this properly. May take a few days as its getting late here in NZ. WGS84 is supported apparently according to the memo.

**Comment by bennahugo** [comment]
ok no problem. I will continue trying to make things more conformant. I think first order we just need to add offsets off the array centre ITRF coordinate?

**Comment by tmolteno** [comment]
This should do. It is simply location.to_geodetic() in the codebase... (location) is the tart position in astropy.

**Comment by bennahugo** [comment]
Tagging @rubyvanrooyen thoughts on the proposed fix?

**Comment by bennahugo** [comment]
I guess the other solid way of testing this is to regenerate UVW coordinates in casa - if we get handedness wrong it should surely show up in the direction vectors... but this is just a thought
