### ISSUE TITLE
Concat json / h5 into single database

### ISSUE THREAD

**Issue by bennahugo** [tart-telescope/tart2ms#16]
Currently one ms is written out per input json / h5. This is not quite ideal. It would be better to have multiple databases concatted into a single database (similar how a casa virtualconcat will work, but less virtual...)

I will need to look into this. I think the way to do this is to rely on the observation table and populate them one per input file and do the correct thing for foreign keys in the main table, offsetting scans, field ids and observation numbers

**Comment by tmolteno** [comment]
We should discuss this at the next meeting.
