### ISSUE TITLE
Add rephasor operator

### ISSUE THREAD

**Issue by bennahugo** [tart-telescope/tart2ms#20]
Really want to have this as a feature, but this will be a bit more involved (probably a good few hours of work)

This is really important to have for deep integration tart images (thinking perhaps on the scale of hours)

**Comment by bennahugo** [comment]
currently you can use casa fixvis with a phase centre applied to all fields, but then casa for some reason I don't fathom does not combine the field ids to a single field FFS. so you need to open it with tb and set field_id to 0 manually (assuming you rephase all the fields)

**Comment by tmolteno** [comment]
I love this feature!!! Never thought I'd hear 'deep integration' used for TART images!!!

**Comment by bennahugo** [comment]
Ok I believe I have it working inside a branch... it took some headscratching to figure out which way goes which when
it comes to the signs but I'm matching Andre Offringas chgcentre routine very well so I'm going to state this is working (CASA's fixvis is known to be a small angle approximation so it is not a good comparison)
![image](https://user-images.githubusercontent.com/7934586/196960159-86361309-9578-4e3e-9536-37c03eacb850.png)
Left is chgcentre and right is tartsoft
