### ISSUE TITLE
Rephase to Sun / Moon / Sgr A*

### ISSUE THREAD

**Issue by bennahugo** [tart-telescope/tart2ms#46]
Add special keywords to rephase to these positions

**Comment by tmolteno** [comment]
I think we need to resolve issue #47 first so see how arbitrary places are specified. Then this becomes a very easy option to add later. 

These are potentially more useful than NCP and SCP which aren't likely to be used for deep sky work!

**Comment by bennahugo** [comment]
Not sure why not though - they are as good as any other celestial position. I have left them as special positions, which are defined as follows:
```json
{
        "name": "SCP",
        "position": {
            "RA": "00h00m00s",
            "DEC": "-90d00m00s",
            "EQUINOX": "J2000",
            "FRAME": "fk5"
        }
}
```
along with positions for e.g. SgrA*

**Comment by bennahugo** [comment]
I will implement solar system bodies now - these require special ephemeris to be computed - the written FITS ephemeris is therefore arbitrary (RA / DEC is ill defined in that frame.
