### ISSUE TITLE
Memo 229 conformance issues

### ISSUE THREAD

**Issue by bennahugo** [tart-telescope/tart2ms#8]
Starting to document conformance / non-compliance issues with tart2ms and the v2 specification here. Will try to address them as I go
- MAIN: Missing interal / exposure
- MAIN: TIME_CENTOID invalid shape - should be row
- MAIN: Missing PROCESSOR_ID, FIELD_ID, SCAN_NUMBER, ARRAY_ID, OBSERVATION_ID, STATE_ID

Incorrect field direction descriptor -- this will only work for a single integration database (the rhodes database contain a number of intervals and each must have zenith correctly referenced (as the centre point of integration) so that rephasing can be possible

I'm defining a convention where each integration will be a rough "tracking scan" for imaging purposes

Currently epoch_s needs to be mapped from timestamps. Will submit a fix soon

**Comment by tmolteno** [comment]
Just fixing this coincidentally. Just done TIME_CENTROID

**Comment by tmolteno** [comment]
There is a function timestamp_to_ms_epoch in the main file. Hopefully this helps with the mapping to epoch_s

**Comment by bennahugo** [comment]
TOPO frame is not set correctly in the data and the total bandwidth is also incorrect

**Comment by bennahugo** [comment]
I think I fixed this in the PR now I'm going to close this unless I run into further problems
